### ISSUE TITLE
Flood by "Error sending message, checkout logs" messages

### ISSUE THREAD

**Issue by strangeman** [inCaller/prometheus_bot#13] opened 2017-03-15 07:35 UTC
**Steps to reproduce**

- use template with map fields, for example (we get `summary` field of CommonAnnotations):
```
Alert {{.Status}}

{{.CommonAnnotations.summary}}
```

- put JSON with empty map, for example
```
###skipped###
      "startsAt": "2017-03-15T09:23:37.861+03:00"
    }
  ],
  "commonAnnotations": {
    
  },
  "commonLabels": {
    "alertname": "low_disk_space",
###skipped###
```

**Expected behavior:** bot sends empty string instead of `{{.CommonAnnotations.summary}}`

**Real behavior:**
- with test suite we got 1 `Error sending message, checkout logs` and 503 error in logs:
```
+---------------  F I N A L   M E S S A G E  ---------------+
Alert firing

<no value>

+-----------------------------------------------------------+
Error sending message: Bad Request
[GIN] 2017/03/15 - 17:06:04 | 503 |  1.585562539s | 127.0.0.1 |   POST    /alert/-XXXXXX

```
- with real Alertmanager we got infinity flood of `Error sending message, checkout logs` messages. Looks like Alertmanager send a POST, got 503, resend POST, got 503 again etc...

**Comment by hryamzik** [comment] 2017-03-15 07:47
Can you post complete json example so I could add it to tests?

**Comment by hryamzik** [comment] 2017-03-15 07:48
Alert manager retries sending alerts if bot fails, that's an expected behavior.

**Comment by strangeman** [comment] 2017-03-15 08:12
Sure. BTW, it will fail with `noGenURL.json` too

empty_value.json
```
{
    "receiver": "admins",
    "status": "firing",
    "alerts": [
        {
            "status": "firing",
            "labels": {
                "alertname": "empty_value",
                "env": "prod",
                "instance": "server01.int:9100",
                "job": "node",
                "service": "prometheus_bot",
                "severity": "warning",
                "supervisor": "runit"
            },
            "annotations": {
                "summary": "Oops, empty value!"
            },
            "startsAt": "2016-04-27T20:46:37.903Z",
            "endsAt": "0001-01-01T00:00:00Z",
            "generatorURL": "https://example.com/graph#..."
        }
    ],
    "groupLabels": {
        "alertname": "empty_value",
        "instance": "server01.int:9100"
    },
    "commonLabels": {
        "alertname": "empty_value",
        "env": "prod",
        "instance": "server01.int:9100",
        "job": "node",
        "service": "prometheus_bot",
        "severity": "warning",
        "supervisor": "runit"
    },
    "commonAnnotations": {

    },
    "externalURL": "https://alert-manager.example.com",
    "version": "3",
    "groupKey": 43434343434343434343
}
```

Do not forget to add template.tmpl:
```
Alert {{.Status}}

{{.CommonAnnotations.summary}}
```

I can fix it and create PR tomorrow if you don't have enough time. It should be easy to fix (add `nil` checking somewhere) :)

**Comment by hryamzik** [comment] 2017-03-15 12:22
That would be great, initial version worked fine with `noGenURL.json`, looks like #7 brought some issues.

I'll create a separate branch to update tests, iterating over `json` files won't here as well.

**Comment by hryamzik** [comment] 2017-03-15 15:41
@strangeman I've created [`templates`](/inCaller/prometheus_bot/tree/templates) branch, please apply your PR there. I've also found another issue #14, it should be fixed to make tests green.

**Comment by hryamzik** [comment] 2017-03-16 11:26
No more food but messages are corrupted:

```
prometheus, [16 Mar 2017 12:22 PM]: 
...Active Alert List:
{map[summary:Oops, something happend!]  https://example.com/graph#... map[service:prometheus_bot severity:warning supervisor:runit alertname:something_happend env:prod instance:server01.int:9100 job:node] 2016-04-27T20:46:37.903Z}

Version:0

Alert firing

Alert resolved

Alert firing

runit service prometheus_bot restarted, server01.int:9100
```

Found this with test 9 – `ok 9 - simpe.json template detailed_vars.tmpl`.

@strangeman do you have this issue as well?

**Comment by strangeman** [comment] 2017-03-17 00:09
Messages aren't corrupted. Look:

In `detailed_vars.tmpl` we send to Telegram two fields:  Alert Status (firing/resolved) and Summary from CommonAnnotations.
```
Alert {{.Status}}

{{.CommonAnnotations.summary}}
```

In  `simpe.json` both fields are persisted and were sent:
```
    "status": "firing",
    ...
    "commonAnnotations": {
        "summary": "runit service prometheus_bot restarted, server01.int:9100"
    },
```

In `noGenURL.json` and `emptyValue.json` `summary` field in `commonAnnotations` wasn't persist and not sent. 

```
    "commonAnnotations": {

    },
```

You can easily check that messages not broken by modifying `detailed_vars.tmpl`:
```
Alert {{.Status}}

Annotations: {{.CommonAnnotations.summary}}

End of message.
```
In first two messages, `commonAnnotations.summary` just not persist and not shown.
![2017-03-17-100556_1366x768_scrot](https://cloud.githubusercontent.com/assets/1083576/24023651/65374194-0af9-11e7-9806-04b76e233b2b.png)

**Comment by hryamzik** [comment] 2017-03-17 00:14
Well, that's what I see in telegram after tests run:
![image](https://cloud.githubusercontent.com/assets/1643962/24023773/c90a0364-0aae-11e7-9705-e4297a157b52.png)

`map[summary:Oops, something happend!]` looks bad for me.

**Comment by hryamzik** [comment] 2017-03-17 00:15
Hey, my bad, it's the real summary, not the compilation error! Closing now. =)

**Closed by hryamzik** 2017-03-17 00:15 UTC
